# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e3949e28c3bf80095c97510bcfeaa68837e2bc0111b60c1ee6cc446ee19a91458f9e55be6669e127233ee24842b1e0dbb0d345fe317899f267ac035fdbc2bb47

test:
  secret_key_base: e77abf92665d679ab59754c1068874efedd9b7357f84c79ba0f8315fedcd513e4b3e1c5b07eac5870f007e93eb19d36bf274e2b876fbfdc09a46c421f18b8ec6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
